#!/usr/bin/env python3
"""Regenerate src/report/logo_data_uri.h from the brand logo.

Reproducible logo-embedding step for the HTML report's cover page. Resizes
the source logo to a report-appropriate resolution, encodes it as a base64
data: URI, and writes it as a chunked C string-literal header so the report
stays a single self-contained file (no external asset reference, survives
email + print-to-PDF) WITHOUT hand-editing base64.

Swapping the logo:
  1. drop the new image in assets/brand/ (update SRC below if the name changes)
  2. run:  python3 assets/brand/make-logo-datauri.py
  3. rebuild -- src/report/report_html.c #includes the generated header.

The string is chunked to stay under C99's 4095-byte string-literal limit
(the project builds -Wpedantic -Werror, which flags -Woverlength-strings);
adjacent C string literals concatenate, so the chunks form one URI.
"""
import base64
import io
import os
import sys

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
SRC = os.path.join(HERE, "cytadelredllogo.jpg")
OUT = os.path.join(ROOT, "src", "report", "logo_data_uri.h")

# Cover-page render size. The logo is square; 240px is crisp on screen and in
# print without inlining a multi-megabyte photo.
SIZE = (240, 240)
JPEG_QUALITY = 86
CHUNK = 4000  # < 4095 so each literal is within the C99 limit
MAX_B64_BYTES = 100 * 1024  # hard ceiling per the brand brief


def main():
    if not os.path.exists(SRC):
        sys.exit("source logo not found: %s" % SRC)

    im = Image.open(SRC).convert("RGB")  # JPG: no alpha; brand bg is solid black
    im = im.resize(SIZE, Image.LANCZOS)
    buf = io.BytesIO()
    im.save(buf, format="JPEG", quality=JPEG_QUALITY, optimize=True)
    raw = buf.getvalue()
    b64 = base64.b64encode(raw).decode("ascii")

    if len(b64) > MAX_B64_BYTES:
        sys.exit("base64 is %d bytes, over the %d ceiling -- lower SIZE/quality"
                 % (len(b64), MAX_B64_BYTES))

    uri = "data:image/jpeg;base64," + b64
    chunks = [uri[i:i + CHUNK] for i in range(0, len(uri), CHUNK)]

    # Emit an ARRAY of separate chunk literals (NOT one concatenated literal):
    # -Woverlength-strings checks the length AFTER adjacent-literal
    # concatenation, so chunks joined with " " " " would still trip it. The
    # renderer appends the array elements in a loop. Each element is < 4095.
    lines = [
        "/* GENERATED by assets/brand/make-logo-datauri.py -- DO NOT EDIT BY HAND.",
        " * Re-run that script after swapping assets/brand/cytadelredllogo.jpg.",
        " * The Cytadel cover-page logo as a self-contained base64 data: URI",
        " * (%dx%d JPEG, %d raw bytes, %d base64 bytes), split into an array of" % (
            SIZE[0], SIZE[1], len(raw), len(b64)),
        " * chunks each under C99's 4095-byte string-literal limit (-Wpedantic).",
        " * The renderer concatenates them into the <img src> at emit time. */",
        "#ifndef CYTADEL_REPORT_LOGO_DATA_URI_H",
        "#define CYTADEL_REPORT_LOGO_DATA_URI_H",
        "",
        "#define CYTADEL_LOGO_DATA_URI_CHUNK_COUNT %d" % len(chunks),
        "",
        "static const char *const CYTADEL_LOGO_DATA_URI_CHUNKS[CYTADEL_LOGO_DATA_URI_CHUNK_COUNT] = {",
    ]
    for ch in chunks:
        lines.append('    "%s",' % ch)
    lines += ["};", "", "#endif /* CYTADEL_REPORT_LOGO_DATA_URI_H */", ""]

    with open(OUT, "w", newline="\n") as f:
        f.write("\n".join(lines))

    print("wrote %s" % OUT)
    print("  render size : %dx%d" % SIZE)
    print("  jpeg bytes  : %d" % len(raw))
    print("  base64 bytes: %d (%.1f KB, ceiling %d KB)" % (
        len(b64), len(b64) / 1024.0, MAX_B64_BYTES // 1024))
    print("  chunks      : %d" % len(chunks))


if __name__ == "__main__":
    main()
